server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/booknplay_auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: user-events
  cache:
    type: caffeine # switch to redis by setting spring.cache.type=redis and enabling redis connection
    cache-names: users
  data:
    redis:
      host: localhost
      port: 6379
caffeine:
  spec: maximumSize=1000,expireAfterAccess=10m
jwt:
  secret: change-me-please-very-long-secret-key
  expirationMinutes: 60
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
