resilience4j:
  ratelimiter:
    instances:
      bookingApi:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 0
  bulkhead:
    instances:
      bookingApi:
        max-concurrent-calls: 100
        max-wait-duration: 0
  circuitbreaker:
    instances:
      bookingApi:
        sliding-window-size: 50
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
